### ISSUE TITLE
Installation Steps

### ISSUE THREAD

**Issue by lounsbrough** [hikirsch/htd_mc-home-assistant#2]
I can't get this installed on my home assistant after moving off of `Home Assistant Core` and onto the standard image. Can you confirm whether there is way to install this on a standard home assistant installation?

The UI provides a way to specify a repo to add as a custom addon, however this repo does not work. Any suggestions would be appreciated.

Thanks!

![image](https://user-images.githubusercontent.com/8313853/105618468-210a9880-5dad-11eb-95ff-4156223e3ce8.png)

**Comment by hikirsch** [comment]
Hi, sorry I don't want to use this as a support forum. Please post this to the community, I've installed this manually into my configurations custom_components folder.
