### ISSUE TITLE
Component fails to load with 2021.6+ because of lack of version

### ISSUE THREAD

**Issue by rogersmj** [hikirsch/htd_mc-home-assistant#3]
After updating to Home Assistant 2021.6, this component will no longer load, presumably because it hasn't been updated to include a version key. Details:

https://github.com/home-assistant/core/pull/49916

**Comment by markus99** [comment]
Personally, before upgrading to 2021.6.x I went thru my custom_components folder and edited the manifest.json file in each - ensuring every one had a `"version" : "20210601"` line added if it didn't already have one, making certain the preceeding line had a `,` at the end

**Comment by hikirsch** [comment]
this is fixed now.
