### ISSUE TITLE
Setup failed for htd_mc: Unable to import component: cannot import name 'Dict' from 'homeassistant.helpers.typing' (/usr/src/homeassistant/homeassistant/helpers/typing.py)

### ISSUE THREAD

**Issue by BrentIO** [hikirsch/htd_mc-home-assistant#4]
With Home Assistant 2022.2.2, the integration is breaking with an error on reboot/restart:

`Setup failed for htd_mc: Unable to import component: cannot import name 'Dict' from 'homeassistant.helpers.typing' (/usr/src/homeassistant/homeassistant/helpers/typing.py)`

Based on the commits, it appears this has been removed from the typing module: https://github.com/home-assistant/core/commit/d3b7bd25ef21e006e4f848f807a79f1573caace6#diff-04ffa15896003585ef538fdf75493426e3ca86537e60e24669c3b472efc3cfd0.

Simply removing the Dict import will correct the issue:

`__init__.py`

```
"""Support for Home Theatre Direct's MC series"""
import voluptuous as vol

from homeassistant.core import HomeAssistant
from homeassistant.helpers import config_validation as cv, discovery
from homeassistant.const import CONF_HOST, CONF_PORT, CONF_PASSWORD, CONF_USERNAME
import homeassistant.helpers.config_validation as cv
from homeassistant.helpers.typing import ConfigType #, Dict
```

**Comment by rogersmj** [comment]
@BrentIO I see you posted this 17 minutes ago....literally just ran into this myself at exactly the same time after an HA upgrade and came here for help. Thank you!

**Comment by markus99** [comment]
Seeing the same.

```
    - Component error: htd_mc - cannot import name 'Dict' from 'homeassistant.helpers.typing' (/usr/local/lib/python3.9/site-packages/homeassistant/helpers/typing.py)
```

**Comment by roechas** [comment]
I just updated my HomeAssistant OS and Core. I am seeing the error above. I commented out that line importing the Dict.
But now I am getting this error
![image](https://user-images.githubusercontent.com/18195153/159386109-b562b94f-493b-41d6-a8c4-3708a4c623c0.png)
Any ideas how to resolve this?

**Comment by roechas** [comment]
![image](https://user-images.githubusercontent.com/18195153/159389192-3088d4f1-45c1-4729-acd2-d587ba910aa7.png)

**Comment by BrentIO** [comment]
@roechas I don’t think you commented out the correct thing, or you also have a configuration issue in addition to this problem. I just upgraded to 2022.3.6 and it continues to work for me using this commented out change. I don’t see anything in my logs and my configuration is still valid.

Please paste the first 10 lines of your __init__.py file from the mtc folder.

**Comment by roechas** [comment]
[image: image.png]
I appreciate your response. I am really not sure what's going on. It was
working fine before I updated the OS.

**Comment by BrentIO** [comment]
> [image: image.png] I appreciate your response. I am really not sure what's going on. It was working fine before I updated the OS.
> […](#)

I don’t see an image attached.

**Comment by roechas** [comment]
![image](https://user-images.githubusercontent.com/18195153/159723294-42245b4f-c52d-4c26-bf05-a2a4e5d26d97.png)

**Comment by BrentIO** [comment]
Yep — you commented out the entire line, which is the problem. Uncomment the last line and comment out just the `, dict` at the end of the last line.  See my example at the top. They should remove your errors and fix the problem as well.

**Comment by roechas** [comment]
Awesome! That did fix it. Its working now.
THANK YOU!

**Comment by hikirsch** [comment]
i'm really sorry guys this took me forever to remove officially that it really should, PR has been merged thanks for letting me know!
