### ISSUE TITLE
HtdDevice using deprecated supported features

### ISSUE THREAD

**Issue by markus99** [hikirsch/htd_mc-home-assistant#7]
Just upgraded to 2024.1 and seeing these error msgs in logs:

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1524
First occurred: 12:45:08 PM (12 occurrences)
Last logged: 12:45:08 PM

Entity None (<class 'custom_components.htd_mc.media_player.HtdDevice'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.VOLUME_SET|VOLUME_MUTE|TURN_ON|TURN_OFF|VOLUME_STEP|SELECT_SOURCE: 3468>, please report it to the author of the 'htd_mc' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

Unfortunately I'm not savvy enough to fix, so posting here.  Thx!

**Comment by markus99** [comment]
Realize there's some time until 2025.1, but wanted to bump this issue.  Thx @hikirsch!

**Comment by hikirsch** [comment]
> Realize there's some time until 2025.1, but wanted to bump this issue.  Thx @hikirsch!

Hey Markus!

Thanks for the ping! I didn't notice this warning thanks for calling it out, I agree I'll find time soon and make these updates, they look simple enough.

Will keep you all posted.

--Adam

**Comment by hikirsch** [comment]
Hey @markus99 can you try updating this from HACS ;-) and let me know how it goes. Once you're able to confirm, I'll close the issue and announce the new HACS integration. Thank you for calling this out!

**Comment by hikirsch** [comment]
closing, will open another issue if there are issues.

**Comment by UngluedChalice** [comment]
So I'm trying to update [my fork which is for HTD Lync 12](https://github.com/UngluedChalice/htd-lync12-home-assistant/blob/master/htd_lync12/media_player.py), but I'm not a programmer at all. Any tips on what needs to change? 

I was thinking these lines need to update, but if I try to fix it by the guess-and-test method, I already know it will never work. 

```
SUPPORT_HTD_Lync12 = (
    SUPPORT_SELECT_SOURCE
    | SUPPORT_TURN_OFF
    | SUPPORT_TURN_ON
    | SUPPORT_VOLUME_MUTE
    | SUPPORT_VOLUME_SET
    #| SUPPORT_VOLUME_STEP
```

Sorry if this is the wrong spot for it, but I'm not sure where else to post.
